/*
 * Copyright (C) 2022 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

require('./basicabilityapi.test.js')
require('./mediaquery.test.js')
require('./commonComponentJsApi.test.js')
require('./divProps.test.js')
require('./buttonProps.test.js')
require('./chartProps.test.js')
require('./imageProps.test.js')
require('./spanProps.test.js')
require('./marqueeProps.test.js')
require('./menuProps.test.js')
require('./switchProps.test.js')
require('./tabsProps.test.js')
require('./tabBarProps.test.js')
require('./tabContentProps.test.js')
require('./progressProps.test.js')
require('./dividerProps.test.js')
require('./optionProps.test.js')
require('./pickerProps.test.js')
require('./pickerViewProps.test.js')
require('./labelProps.test.js')
require('./stackProps.test.js')
require('./panelProps.test.js')
require('./pieceProps.test.js')
require('./refreshProps.test.js')
require('./swiperProps.test.js')
require('./textProps.test.js')
require('./popupProps.test.js')
require('./badgeProps.test.js')
require('./dialogProps.test.js')
require('./formProps.test.js')
require('./listProps.test.js')
require('./listItemProps.test.js')
require('./listItemGroupProps.test.js')
require('./stepperProps.test.js')
require('./stepperItemProps.test.js')
require('./searchProps.test.js')
require('./selectProps.test.js')
require('./sliderProps.test.js')
require('./ratingProps.test.js')
require('./inputProps.test.js')
require('./imageAnimatorProps.test.js')
require('./textareaProps.test.js')
require('./videoProps.test.js')
require('./gridContainerProps.test.js')
require('./svgProps.test.js')
require('./rectProps.test.js')
require('./circleProps.test.js')
require('./qrcodeProps.test.js')
require('./richtextProps.test.js')
require('./toggleProps.test.js')
require('./toolbarProps.test.js')
require('./toolbarItemProps.test.js')
require('./gridColProps.test.js')
require('./gridRowProps.test.js')
require('./ellipseProps.test.js')
require('./pathProps.test.js')
require('./lineProps.test.js')
require('./polylineProps.test.js')
require('./polygonProps.test.js')
require('./svgTextProps.test.js')
require('./tspanProps.test.js')
require('./textPathProps.test.js')
require('./animateProps.test.js')
require('./animateMotionProps.test.js')
require('./animateTransformProps.test.js')
require('./canvasProps.test.js')