/*
 * Copyright (c) 2021 Huawei Device Co., Ltd.
 *
 * HDF is dual licensed: you can use it either under the terms of
 * the GPL, or the BSD license, at your option.
 * See the LICENSE file in the root of this repository for complete details.
 */

package test.kernel_test.list_test.v1_0;

import test.kernel_test.list_test.v1_0.ListTypes;

interface IListTest {

    BoolListTest([in] List<boolean> param1, [out] List<boolean> param2);

    ByteListTest([in] List<byte> param1, [out] List<byte> param2);

    ShortListTest([in] List<short> param1, [out] List<short> param2);

    IntListTest([in] List<int> param1, [out] List<int> param2);

    LongListTest([in] List<long> param1, [out] List<long> param2);

    UCharListTest([in] List<unsigned char> param1, [out] List<unsigned char> param2);

    UShortListTest([in] List<unsigned short> param1, [out] List<unsigned short> param2);

    UIntListTest([in] List<unsigned int> param1, [out] List<unsigned int> param2);

    ULongListTest([in] List<unsigned long> param1, [out] List<unsigned long> param2);

    StringListTest([in] List<String> param1, [out] List<String> param2);

    EnumListTest([in] List<enum LESample> param1, [out] List<enum LESample> param2);

    StructListTest([in] List<struct LSSample> param1, [out] List<struct LSSample> param2);

    UnionListTest([in] List<union LUSample> param1, [out] List<union LUSample> param2);
}