/*
 *
 * Automatically generated file; DO NOT EDIT.
 * Huawei LiteOS Configuration
 *
 */
#define LOSCFG_PRODUCT_NAME "bes2600w"
#define LOSCFG_KERNEL_SMP_CORE_NUM 2
#define LOSCFG_CC_STACKPROTECTOR_STRONG 1
#define LOSCFG_PRODUCT_BES2300W 1
#define LOSCFG_PLATFORM "bes2600w"
#define LOSCFG_PLATFORM_BSP_GIC_V2 1
#define LOSCFG_BOARD_CONFIG_PATH "config/board"
#define LOSCFG_PLATFORM_UART_WITHOUT_VFS 1
#define LOSCFG_PLATFORM_BES2300W 1
#define LOSCFG_ARCH_CORTEX_A7 1
#define LOSCFG_ARCH_ARM_VER "armv7-a"
#define LOSCFG_IRQ_USE_STANDALONE_STACK 1
#define LOSCFG_ARCH_ARM_AARCH32 1
#define LOSCFG_ARCH_CPU "cortex-a7"
#define LOSCFG_ARCH_ARM_V7A 1
#define LOSCFG_ARCH_FPU "neon-vfpv4"
#define LOSCFG_ARCH_FPU_VFP_D32 1
#define LOSCFG_COMPILER_ARM_GCC 1
#define LOSCFG_ARCH_ARM 1
#define LOSCFG_KERNEL_SMP 1
#define LOSCFG_ARCH_FPU_VFP_NEON 1
#define LOSCFG_COMPILE_DEBUG 1
#define LOSCFG_DEVICE_COMPANY "bestechnic"
#define LOSCFG_ARCH_FPU_VFP_V4 1
#define LOSCFG_LIB_LIBC 1
#define LOSCFG_ARCH_GIC_V2 1
#define LOSCFG_DRIVERS 1
#define LOSCFG_NO_SHARED_IRQ 1
#define LOSCFG_KERNEL_EXTKERNEL 1
#define LOSCFG_KERNEL_CPPSUPPORT 1
#define LOSCFG_KERNEL_CPUP 1
#define LOSCFG_CPUP_INCLUDE_IRQ 1
#define LOSCFG_PLATFORM_ADAPT 1
#define LOSCFG_BASE_IPC_MUX 1
#define LOSCFG_BASE_IPC_SEM 1
#define LOSCFG_BASE_IPC_QUEUE 1