obj-y := src/

subdir-ccflags-y += -DLWIP_DEBUG
subdir-ccflags-y += \
    -I$(LWIP_ROOT)/src/include/\
    -I$(LWIP_ROOT)/src/include/lwip/\
    -I$(LWIP_ROOT)/src/include/lwip/arch\
    -Inet/include/os/\
    -Iplatform/hal/\
    -Iplatform/cmsis/inc\
    -Inet/include/\
    -Irtos/rtx/TARGET_CORTEX_M/\
    -Inet/\
    -Inet/include/\
    -Inet/include/byteorder/\
    -Inet/include/os/\
    -Inet/include/unaligned/\
    -Inet/net80211/\
    -Inet/core/\
    -Inet/net_os/
