# This is the wrapper of lplayer, NEVER use lplayer directly.
include $(srctree)/scripts/common.mk


obj-y := $(src_obj)


ccflags-y += -Iservices/lplayer/interface/include -Iservices/bt_app -Iplatform/drivers \
	-Iservices/resources \
	-Iapps/key -Iservices/bt_if_enhanced/inc -Iutils/cqueue \
	-Iservices/multimedia/audio/codec/sbc/inc \
	-Iservices/multimedia/audio/codec/sbc/src/inc \
	-Iservices/bt_app -Iservices/bt_app/a2dp_codecs/include -Iapps/besfd_api


