obj-y += animimg/ \
    calendar/ \
    chart/ \
    colorwheel/ \
    imgbtn/ \
    keyboard/ \
    led/ \
    list/ \
    meter/ \
    msgbox/ \
    span/ \
    spinbox/ \
    spinner/ \
    tabview/ \
    tileview/ \
    lvwin_/