obj-y := lvgl/ lv_logo/ lv_port/ ${LV_PROJ}/

export LVGL_DIR := gui/lvgl
subdir-ccflags-y += \
    -Igui/\
    -Igui/${LV_PROJ}/\
    -Igui/lv_port/display/\
    -Igui/lv_port/indev/\
    -Igui/lv_port//indev/platform/\
    -Igui/lvgl/\
    -Igui/lvgl/demos/\
    -Igui/lvgl/src/\
    -Iservices/wifi_app/littlefs/flash_partition/
    
