/*
 * Copyright (c) 2021 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Automatically generated file; DO NOT EDIT.

#include "frameworks/bridge/js_frontend/engine/quickjs/intl/intl_support.h"

std::unordered_map<std::string, std::vector<const void*>> g_localeDatas = {
    { "intl_en", std::vector<const void*> {static_cast<const void*>(&intl_en_size),
        static_cast<const void*>(intl_en)} },
    { "intl_relative_en", std::vector<const void*> {static_cast<const void*>(&intl_relative_en_size),
        static_cast<const void*>(intl_relative_en)} },
    { "intl_ar", std::vector<const void*> {static_cast<const void*>(&intl_ar_size),
        static_cast<const void*>(intl_ar)} },
    { "intl_relative_ar", std::vector<const void*> {static_cast<const void*>(&intl_relative_ar_size),
        static_cast<const void*>(intl_relative_ar)} },
    { "intl_az", std::vector<const void*> {static_cast<const void*>(&intl_az_size),
        static_cast<const void*>(intl_az)} },
    { "intl_relative_az", std::vector<const void*> {static_cast<const void*>(&intl_relative_az_size),
        static_cast<const void*>(intl_relative_az)} },
    { "intl_be", std::vector<const void*> {static_cast<const void*>(&intl_be_size),
        static_cast<const void*>(intl_be)} },
    { "intl_relative_be", std::vector<const void*> {static_cast<const void*>(&intl_relative_be_size),
        static_cast<const void*>(intl_relative_be)} },
    { "intl_bg", std::vector<const void*> {static_cast<const void*>(&intl_bg_size),
        static_cast<const void*>(intl_bg)} },
    { "intl_relative_bg", std::vector<const void*> {static_cast<const void*>(&intl_relative_bg_size),
        static_cast<const void*>(intl_relative_bg)} },
    { "intl_bn", std::vector<const void*> {static_cast<const void*>(&intl_bn_size),
        static_cast<const void*>(intl_bn)} },
    { "intl_relative_bn", std::vector<const void*> {static_cast<const void*>(&intl_relative_bn_size),
        static_cast<const void*>(intl_relative_bn)} },
    { "intl_bo_CN", std::vector<const void*> {static_cast<const void*>(&intl_bo_CN_size),
        static_cast<const void*>(intl_bo_CN)} },
    { "intl_relative_bo_CN", std::vector<const void*> {static_cast<const void*>(&intl_relative_bo_CN_size),
        static_cast<const void*>(intl_relative_bo_CN)} },
    { "intl_bs", std::vector<const void*> {static_cast<const void*>(&intl_bs_size),
        static_cast<const void*>(intl_bs)} },
    { "intl_relative_bs", std::vector<const void*> {static_cast<const void*>(&intl_relative_bs_size),
        static_cast<const void*>(intl_relative_bs)} },
    { "intl_ca", std::vector<const void*> {static_cast<const void*>(&intl_ca_size),
        static_cast<const void*>(intl_ca)} },
    { "intl_relative_ca", std::vector<const void*> {static_cast<const void*>(&intl_relative_ca_size),
        static_cast<const void*>(intl_relative_ca)} },
    { "intl_cs", std::vector<const void*> {static_cast<const void*>(&intl_cs_size),
        static_cast<const void*>(intl_cs)} },
    { "intl_relative_cs", std::vector<const void*> {static_cast<const void*>(&intl_relative_cs_size),
        static_cast<const void*>(intl_relative_cs)} },
    { "intl_da", std::vector<const void*> {static_cast<const void*>(&intl_da_size),
        static_cast<const void*>(intl_da)} },
    { "intl_relative_da", std::vector<const void*> {static_cast<const void*>(&intl_relative_da_size),
        static_cast<const void*>(intl_relative_da)} },
    { "intl_de", std::vector<const void*> {static_cast<const void*>(&intl_de_size),
        static_cast<const void*>(intl_de)} },
    { "intl_relative_de", std::vector<const void*> {static_cast<const void*>(&intl_relative_de_size),
        static_cast<const void*>(intl_relative_de)} },
    { "intl_el", std::vector<const void*> {static_cast<const void*>(&intl_el_size),
        static_cast<const void*>(intl_el)} },
    { "intl_relative_el", std::vector<const void*> {static_cast<const void*>(&intl_relative_el_size),
        static_cast<const void*>(intl_relative_el)} },
    { "intl_en_GB", std::vector<const void*> {static_cast<const void*>(&intl_en_GB_size),
        static_cast<const void*>(intl_en_GB)} },
    { "intl_relative_en_GB", std::vector<const void*> {static_cast<const void*>(&intl_relative_en_GB_size),
        static_cast<const void*>(intl_relative_en_GB)} },
    { "intl_es", std::vector<const void*> {static_cast<const void*>(&intl_es_size),
        static_cast<const void*>(intl_es)} },
    { "intl_relative_es", std::vector<const void*> {static_cast<const void*>(&intl_relative_es_size),
        static_cast<const void*>(intl_relative_es)} },
    { "intl_es_US", std::vector<const void*> {static_cast<const void*>(&intl_es_US_size),
        static_cast<const void*>(intl_es_US)} },
    { "intl_relative_es_US", std::vector<const void*> {static_cast<const void*>(&intl_relative_es_US_size),
        static_cast<const void*>(intl_relative_es_US)} },
    { "intl_et", std::vector<const void*> {static_cast<const void*>(&intl_et_size),
        static_cast<const void*>(intl_et)} },
    { "intl_relative_et", std::vector<const void*> {static_cast<const void*>(&intl_relative_et_size),
        static_cast<const void*>(intl_relative_et)} },
    { "intl_eu", std::vector<const void*> {static_cast<const void*>(&intl_eu_size),
        static_cast<const void*>(intl_eu)} },
    { "intl_relative_eu", std::vector<const void*> {static_cast<const void*>(&intl_relative_eu_size),
        static_cast<const void*>(intl_relative_eu)} },
    { "intl_fa", std::vector<const void*> {static_cast<const void*>(&intl_fa_size),
        static_cast<const void*>(intl_fa)} },
    { "intl_relative_fa", std::vector<const void*> {static_cast<const void*>(&intl_relative_fa_size),
        static_cast<const void*>(intl_relative_fa)} },
    { "intl_fi", std::vector<const void*> {static_cast<const void*>(&intl_fi_size),
        static_cast<const void*>(intl_fi)} },
    { "intl_relative_fi", std::vector<const void*> {static_cast<const void*>(&intl_relative_fi_size),
        static_cast<const void*>(intl_relative_fi)} },
    { "intl_fr", std::vector<const void*> {static_cast<const void*>(&intl_fr_size),
        static_cast<const void*>(intl_fr)} },
    { "intl_relative_fr", std::vector<const void*> {static_cast<const void*>(&intl_relative_fr_size),
        static_cast<const void*>(intl_relative_fr)} },
    { "intl_gl", std::vector<const void*> {static_cast<const void*>(&intl_gl_size),
        static_cast<const void*>(intl_gl)} },
    { "intl_relative_gl", std::vector<const void*> {static_cast<const void*>(&intl_relative_gl_size),
        static_cast<const void*>(intl_relative_gl)} },
    { "intl_hi", std::vector<const void*> {static_cast<const void*>(&intl_hi_size),
        static_cast<const void*>(intl_hi)} },
    { "intl_relative_hi", std::vector<const void*> {static_cast<const void*>(&intl_relative_hi_size),
        static_cast<const void*>(intl_relative_hi)} },
    { "intl_hr", std::vector<const void*> {static_cast<const void*>(&intl_hr_size),
        static_cast<const void*>(intl_hr)} },
    { "intl_relative_hr", std::vector<const void*> {static_cast<const void*>(&intl_relative_hr_size),
        static_cast<const void*>(intl_relative_hr)} },
    { "intl_hu", std::vector<const void*> {static_cast<const void*>(&intl_hu_size),
        static_cast<const void*>(intl_hu)} },
    { "intl_relative_hu", std::vector<const void*> {static_cast<const void*>(&intl_relative_hu_size),
        static_cast<const void*>(intl_relative_hu)} },
    { "intl_it", std::vector<const void*> {static_cast<const void*>(&intl_it_size),
        static_cast<const void*>(intl_it)} },
    { "intl_relative_it", std::vector<const void*> {static_cast<const void*>(&intl_relative_it_size),
        static_cast<const void*>(intl_relative_it)} },
    { "intl_ja", std::vector<const void*> {static_cast<const void*>(&intl_ja_size),
        static_cast<const void*>(intl_ja)} },
    { "intl_relative_ja", std::vector<const void*> {static_cast<const void*>(&intl_relative_ja_size),
        static_cast<const void*>(intl_relative_ja)} },
    { "intl_ka", std::vector<const void*> {static_cast<const void*>(&intl_ka_size),
        static_cast<const void*>(intl_ka)} },
    { "intl_relative_ka", std::vector<const void*> {static_cast<const void*>(&intl_relative_ka_size),
        static_cast<const void*>(intl_relative_ka)} },
    { "intl_kk", std::vector<const void*> {static_cast<const void*>(&intl_kk_size),
        static_cast<const void*>(intl_kk)} },
    { "intl_relative_kk", std::vector<const void*> {static_cast<const void*>(&intl_relative_kk_size),
        static_cast<const void*>(intl_relative_kk)} },
    { "intl_km", std::vector<const void*> {static_cast<const void*>(&intl_km_size),
        static_cast<const void*>(intl_km)} },
    { "intl_relative_km", std::vector<const void*> {static_cast<const void*>(&intl_relative_km_size),
        static_cast<const void*>(intl_relative_km)} },
    { "intl_ko", std::vector<const void*> {static_cast<const void*>(&intl_ko_size),
        static_cast<const void*>(intl_ko)} },
    { "intl_relative_ko", std::vector<const void*> {static_cast<const void*>(&intl_relative_ko_size),
        static_cast<const void*>(intl_relative_ko)} },
    { "intl_lo", std::vector<const void*> {static_cast<const void*>(&intl_lo_size),
        static_cast<const void*>(intl_lo)} },
    { "intl_relative_lo", std::vector<const void*> {static_cast<const void*>(&intl_relative_lo_size),
        static_cast<const void*>(intl_relative_lo)} },
    { "intl_lt", std::vector<const void*> {static_cast<const void*>(&intl_lt_size),
        static_cast<const void*>(intl_lt)} },
    { "intl_relative_lt", std::vector<const void*> {static_cast<const void*>(&intl_relative_lt_size),
        static_cast<const void*>(intl_relative_lt)} },
    { "intl_lv", std::vector<const void*> {static_cast<const void*>(&intl_lv_size),
        static_cast<const void*>(intl_lv)} },
    { "intl_relative_lv", std::vector<const void*> {static_cast<const void*>(&intl_relative_lv_size),
        static_cast<const void*>(intl_relative_lv)} },
    { "intl_mk", std::vector<const void*> {static_cast<const void*>(&intl_mk_size),
        static_cast<const void*>(intl_mk)} },
    { "intl_relative_mk", std::vector<const void*> {static_cast<const void*>(&intl_relative_mk_size),
        static_cast<const void*>(intl_relative_mk)} },
    { "intl_ms", std::vector<const void*> {static_cast<const void*>(&intl_ms_size),
        static_cast<const void*>(intl_ms)} },
    { "intl_relative_ms", std::vector<const void*> {static_cast<const void*>(&intl_relative_ms_size),
        static_cast<const void*>(intl_relative_ms)} },
    { "intl_my_MM", std::vector<const void*> {static_cast<const void*>(&intl_my_MM_size),
        static_cast<const void*>(intl_my_MM)} },
    { "intl_relative_my_MM", std::vector<const void*> {static_cast<const void*>(&intl_relative_my_MM_size),
        static_cast<const void*>(intl_relative_my_MM)} },
    { "intl_nb", std::vector<const void*> {static_cast<const void*>(&intl_nb_size),
        static_cast<const void*>(intl_nb)} },
    { "intl_relative_nb", std::vector<const void*> {static_cast<const void*>(&intl_relative_nb_size),
        static_cast<const void*>(intl_relative_nb)} },
    { "intl_ne", std::vector<const void*> {static_cast<const void*>(&intl_ne_size),
        static_cast<const void*>(intl_ne)} },
    { "intl_relative_ne", std::vector<const void*> {static_cast<const void*>(&intl_relative_ne_size),
        static_cast<const void*>(intl_relative_ne)} },
    { "intl_nl", std::vector<const void*> {static_cast<const void*>(&intl_nl_size),
        static_cast<const void*>(intl_nl)} },
    { "intl_relative_nl", std::vector<const void*> {static_cast<const void*>(&intl_relative_nl_size),
        static_cast<const void*>(intl_relative_nl)} },
    { "intl_pl", std::vector<const void*> {static_cast<const void*>(&intl_pl_size),
        static_cast<const void*>(intl_pl)} },
    { "intl_relative_pl", std::vector<const void*> {static_cast<const void*>(&intl_relative_pl_size),
        static_cast<const void*>(intl_relative_pl)} },
    { "intl_pt", std::vector<const void*> {static_cast<const void*>(&intl_pt_size),
        static_cast<const void*>(intl_pt)} },
    { "intl_relative_pt", std::vector<const void*> {static_cast<const void*>(&intl_relative_pt_size),
        static_cast<const void*>(intl_relative_pt)} },
    { "intl_pt_PT", std::vector<const void*> {static_cast<const void*>(&intl_pt_PT_size),
        static_cast<const void*>(intl_pt_PT)} },
    { "intl_relative_pt_PT", std::vector<const void*> {static_cast<const void*>(&intl_relative_pt_PT_size),
        static_cast<const void*>(intl_relative_pt_PT)} },
    { "intl_ro", std::vector<const void*> {static_cast<const void*>(&intl_ro_size),
        static_cast<const void*>(intl_ro)} },
    { "intl_relative_ro", std::vector<const void*> {static_cast<const void*>(&intl_relative_ro_size),
        static_cast<const void*>(intl_relative_ro)} },
    { "intl_ru", std::vector<const void*> {static_cast<const void*>(&intl_ru_size),
        static_cast<const void*>(intl_ru)} },
    { "intl_relative_ru", std::vector<const void*> {static_cast<const void*>(&intl_relative_ru_size),
        static_cast<const void*>(intl_relative_ru)} },
    { "intl_si", std::vector<const void*> {static_cast<const void*>(&intl_si_size),
        static_cast<const void*>(intl_si)} },
    { "intl_relative_si", std::vector<const void*> {static_cast<const void*>(&intl_relative_si_size),
        static_cast<const void*>(intl_relative_si)} },
    { "intl_sk", std::vector<const void*> {static_cast<const void*>(&intl_sk_size),
        static_cast<const void*>(intl_sk)} },
    { "intl_relative_sk", std::vector<const void*> {static_cast<const void*>(&intl_relative_sk_size),
        static_cast<const void*>(intl_relative_sk)} },
    { "intl_sl", std::vector<const void*> {static_cast<const void*>(&intl_sl_size),
        static_cast<const void*>(intl_sl)} },
    { "intl_relative_sl", std::vector<const void*> {static_cast<const void*>(&intl_relative_sl_size),
        static_cast<const void*>(intl_relative_sl)} },
    { "intl_sr", std::vector<const void*> {static_cast<const void*>(&intl_sr_size),
        static_cast<const void*>(intl_sr)} },
    { "intl_relative_sr", std::vector<const void*> {static_cast<const void*>(&intl_relative_sr_size),
        static_cast<const void*>(intl_relative_sr)} },
    { "intl_sv", std::vector<const void*> {static_cast<const void*>(&intl_sv_size),
        static_cast<const void*>(intl_sv)} },
    { "intl_relative_sv", std::vector<const void*> {static_cast<const void*>(&intl_relative_sv_size),
        static_cast<const void*>(intl_relative_sv)} },
    { "intl_th", std::vector<const void*> {static_cast<const void*>(&intl_th_size),
        static_cast<const void*>(intl_th)} },
    { "intl_relative_th", std::vector<const void*> {static_cast<const void*>(&intl_relative_th_size),
        static_cast<const void*>(intl_relative_th)} },
    { "intl_tr", std::vector<const void*> {static_cast<const void*>(&intl_tr_size),
        static_cast<const void*>(intl_tr)} },
    { "intl_relative_tr", std::vector<const void*> {static_cast<const void*>(&intl_relative_tr_size),
        static_cast<const void*>(intl_relative_tr)} },
    { "intl_uk", std::vector<const void*> {static_cast<const void*>(&intl_uk_size),
        static_cast<const void*>(intl_uk)} },
    { "intl_relative_uk", std::vector<const void*> {static_cast<const void*>(&intl_relative_uk_size),
        static_cast<const void*>(intl_relative_uk)} },
    { "intl_ur", std::vector<const void*> {static_cast<const void*>(&intl_ur_size),
        static_cast<const void*>(intl_ur)} },
    { "intl_relative_ur", std::vector<const void*> {static_cast<const void*>(&intl_relative_ur_size),
        static_cast<const void*>(intl_relative_ur)} },
    { "intl_uz", std::vector<const void*> {static_cast<const void*>(&intl_uz_size),
        static_cast<const void*>(intl_uz)} },
    { "intl_relative_uz", std::vector<const void*> {static_cast<const void*>(&intl_relative_uz_size),
        static_cast<const void*>(intl_relative_uz)} },
    { "intl_vi", std::vector<const void*> {static_cast<const void*>(&intl_vi_size),
        static_cast<const void*>(intl_vi)} },
    { "intl_relative_vi", std::vector<const void*> {static_cast<const void*>(&intl_relative_vi_size),
        static_cast<const void*>(intl_relative_vi)} },
    { "intl_zh", std::vector<const void*> {static_cast<const void*>(&intl_zh_size),
        static_cast<const void*>(intl_zh)} },
    { "intl_relative_zh", std::vector<const void*> {static_cast<const void*>(&intl_relative_zh_size),
        static_cast<const void*>(intl_relative_zh)} },
    { "intl_zh_Hans_HK", std::vector<const void*> {static_cast<const void*>(&intl_zh_Hans_HK_size),
        static_cast<const void*>(intl_zh_Hans_HK)} },
    { "intl_relative_zh_Hans_HK", std::vector<const void*> {static_cast<const void*>(&intl_relative_zh_Hans_HK_size),
        static_cast<const void*>(intl_relative_zh_Hans_HK)} },
    { "intl_zh_Hant_TW", std::vector<const void*> {static_cast<const void*>(&intl_zh_Hant_TW_size),
        static_cast<const void*>(intl_zh_Hant_TW)} },
    { "intl_relative_zh_Hant_TW", std::vector<const void*> {static_cast<const void*>(&intl_relative_zh_Hant_TW_size),
        static_cast<const void*>(intl_relative_zh_Hant_TW)} },
    { "intl_mn", std::vector<const void*> {static_cast<const void*>(&intl_mn_size),
        static_cast<const void*>(intl_mn)} },
    { "intl_relative_mn", std::vector<const void*> {static_cast<const void*>(&intl_relative_mn_size),
        static_cast<const void*>(intl_relative_mn)} },
    { "intl_sw", std::vector<const void*> {static_cast<const void*>(&intl_sw_size),
        static_cast<const void*>(intl_sw)} },
    { "intl_relative_sw", std::vector<const void*> {static_cast<const void*>(&intl_relative_sw_size),
        static_cast<const void*>(intl_relative_sw)} },
    { "intl_am", std::vector<const void*> {static_cast<const void*>(&intl_am_size),
        static_cast<const void*>(intl_am)} },
    { "intl_relative_am", std::vector<const void*> {static_cast<const void*>(&intl_relative_am_size),
        static_cast<const void*>(intl_relative_am)} },
    { "intl_or", std::vector<const void*> {static_cast<const void*>(&intl_or_size),
        static_cast<const void*>(intl_or)} },
    { "intl_relative_or", std::vector<const void*> {static_cast<const void*>(&intl_relative_or_size),
        static_cast<const void*>(intl_relative_or)} },
    { "intl_as", std::vector<const void*> {static_cast<const void*>(&intl_as_size),
        static_cast<const void*>(intl_as)} },
    { "intl_relative_as", std::vector<const void*> {static_cast<const void*>(&intl_relative_as_size),
        static_cast<const void*>(intl_relative_as)} },
    { "intl_pa", std::vector<const void*> {static_cast<const void*>(&intl_pa_size),
        static_cast<const void*>(intl_pa)} },
    { "intl_relative_pa", std::vector<const void*> {static_cast<const void*>(&intl_relative_pa_size),
        static_cast<const void*>(intl_relative_pa)} },
    { "intl_ta", std::vector<const void*> {static_cast<const void*>(&intl_ta_size),
        static_cast<const void*>(intl_ta)} },
    { "intl_relative_ta", std::vector<const void*> {static_cast<const void*>(&intl_relative_ta_size),
        static_cast<const void*>(intl_relative_ta)} },
    { "intl_ml", std::vector<const void*> {static_cast<const void*>(&intl_ml_size),
        static_cast<const void*>(intl_ml)} },
    { "intl_relative_ml", std::vector<const void*> {static_cast<const void*>(&intl_relative_ml_size),
        static_cast<const void*>(intl_relative_ml)} },
    { "intl_kn", std::vector<const void*> {static_cast<const void*>(&intl_kn_size),
        static_cast<const void*>(intl_kn)} },
    { "intl_relative_kn", std::vector<const void*> {static_cast<const void*>(&intl_relative_kn_size),
        static_cast<const void*>(intl_relative_kn)} },
    { "intl_gu", std::vector<const void*> {static_cast<const void*>(&intl_gu_size),
        static_cast<const void*>(intl_gu)} },
    { "intl_relative_gu", std::vector<const void*> {static_cast<const void*>(&intl_relative_gu_size),
        static_cast<const void*>(intl_relative_gu)} },
    { "intl_mr", std::vector<const void*> {static_cast<const void*>(&intl_mr_size),
        static_cast<const void*>(intl_mr)} },
    { "intl_relative_mr", std::vector<const void*> {static_cast<const void*>(&intl_relative_mr_size),
        static_cast<const void*>(intl_relative_mr)} },
    { "intl_te", std::vector<const void*> {static_cast<const void*>(&intl_te_size),
        static_cast<const void*>(intl_te)} },
    { "intl_relative_te", std::vector<const void*> {static_cast<const void*>(&intl_relative_te_size),
        static_cast<const void*>(intl_relative_te)} },
    { "intl_zh_Hans_CN", std::vector<const void*> {static_cast<const void*>(&intl_zh_Hans_CN_size),
        static_cast<const void*>(intl_zh_Hans_CN)} },
    { "intl_relative_zh_Hans_CN", std::vector<const void*> {static_cast<const void*>(&intl_relative_zh_Hans_CN_size),
        static_cast<const void*>(intl_relative_zh_Hans_CN)} },
    { "intl_en_US", std::vector<const void*> {static_cast<const void*>(&intl_en_US_size),
        static_cast<const void*>(intl_en_US)} },
    { "intl_relative_en_US", std::vector<const void*> {static_cast<const void*>(&intl_relative_en_US_size),
        static_cast<const void*>(intl_relative_en_US)} },
    { "intl_de_DE", std::vector<const void*> {static_cast<const void*>(&intl_de_DE_size),
        static_cast<const void*>(intl_de_DE)} },
    { "intl_relative_de_DE", std::vector<const void*> {static_cast<const void*>(&intl_relative_de_DE_size),
        static_cast<const void*>(intl_relative_de_DE)} },
    { "intl_ja_JP", std::vector<const void*> {static_cast<const void*>(&intl_ja_JP_size),
        static_cast<const void*>(intl_ja_JP)} },
    { "intl_relative_ja_JP", std::vector<const void*> {static_cast<const void*>(&intl_relative_ja_JP_size),
        static_cast<const void*>(intl_relative_ja_JP)} },
};

std::unordered_map<std::string, std::vector<const void*>> GetLocaleDatasMap()
{
    return g_localeDatas;
}
