/*
 * Copyright (c) 2021 Huawei Device Co., Ltd.
 *
 * HDF is dual licensed: you can use it either under the terms of
 * the GPL, or the BSD license, at your option.
 * See the LICENSE file in the root of this repository for complete details.
 */

#ifndef HI3516_AUDIO_DRIVER_TEST_H
#define HI3516_AUDIO_DRIVER_TEST_H

const int G_TEST_HI3516_AUDIO_DRIVER_TYPE    = 702;

typedef enum {
    TESTDAIDEVICEINIT,
    TESTDAISTARTUP,
    TESTDAIHWPARAMS,
    TESTDAITRIGGER,

    TESTCODECHALSYSINIT,
    TESTACODECREGBITSREAD,
    TESTCODECREGBITSUPDATE,
    TESTCODECREGDEFAULTINIT,
    TESTCODECSETADCTUNEENABLE,
    TESTCODECDAIPARAMSUPDATE,
    TESTAUDIOCODECAIAOSETCTRLOPS,

    TESTAUDIOCODECAIAOGETCTRLOPS,
    TESTCODECDEVICEINIT,
    TESTCODECDAIDEVICEINIT,
    TESTCODECDAIHWPARAMS,
    TESTCODECDAISTARTUP,

    TESTAIOPREGCFG,
    TESTAIAOHALSYSINIT,
    TESTAIAOCLOCKRESET,
    TESTAIAOHALREADREG,
    TESTAOPHALSETBUFFRPTR,
    TESTAOPHALSETBUFFWPTR,
    TESTAIPHALSETBUFFWPTR,
    TESTAIPHALSETBUFFRPTR,
    TESTAOPHALSETTXSTART,
    TESTAIPHALSETRXSTART,
    TESTAOPHALDEVENABLE,
    TESTAIAODEVICEINIT,
    TESTAUDIOAOINIT,
    TESTAUDIOAIINIT,
    TESTAIAOSYSPINMUX,
    TESTAIAOGETMCLK,
    TESTAIAOSETSYSCTLREGVALUE,
    TESTAUDIODMADEVICEINIT,
    TESTHI3516DMABUFALLOC,

    TESTHI3516DMABUFFREE,
    TESTHI3516DMAREQUESTCHANNEL,
    TESTHI3516DMACONFIGCHANNEL,
    TESTHI3516DMAPREP,
    TESTHI3516DMASUBMIT,
    TESTHI3516DMAPENDING,
    TESTHI3516DMAPAUSE,
    TESTHI3516DMARESUME,
    TESTHI3516DMAPOINTER,
} HdfHi3516AudioDriverTestCmd;

#endif /* HI3516_AUDIO_DRIVER_TEST_H */
