cur_dir := $(dir $(lastword $(MAKEFILE_LIST)))

obj-y := cmsis/ drivers/ hal/

ifneq ($(DUAL_BOOT),1)
ifneq ($(WIFI_RAMRUN),1)
obj-y += main/
endif
endif

ifeq ($(BECO),1)
obj-y += beco/
endif

subdir-ccflags-y += -Iplatform/cmsis/inc -Iplatform/hal -Iutils/hwtimer_list -Iplatform/drivers/wifi/$(CHIP)

