/*
 * Copyright (c) 2021 Huawei Device Co., Ltd.
 *
 * HDF is dual licensed: you can use it either under the terms of
 * the GPL, or the BSD license, at your option.
 * See the LICENSE file in the root of this repository for complete details.
 */

#ifndef AUDIO_COMMON_TEST_H
#define AUDIO_COMMON_TEST_H

#include "hdf_types.h"

const int32_t g_testAudioType = 701; // 701 is TEST_AUDIO_TYPE

enum HDFAudioTestCommonCmd {
    TESTI2CREADWRITE = 48,
    TESTREGBITSREAD,
    TESTREGBITSUPDATE,
    TESTDEVICEFREQUENCYPARSE,
    TESTDAIPARAMSUPDATE,
    TESTDEVICECFGGET,
    TESTDEVICECTRLREGINIT,
    TESTDEVICEREGREAD,
    TESTDEVICEREGWRITE,
    TESTAGETCONFIGINFO,

    TESTGETSERVICENAME,
    TESTGETDAINAME,
    TESTGETCONFIGINFO,
    TESTSETCONFIGINFO,
    TESTSETCTLFUNC,

    TESTDAIDATAFROMCARD,
    TESTDAIGETCONFIGINFO,
    TESTDAICHECKSAMPLERATE,
    TESTDAISETCONFIGINFO,

    TESTDMABUFALLOC,
    TESTDMABUFFREE,
    TESTDMAREQUESTCHANNEL,
    TESTDMACONFIGCHANNEL,
    TESTDMAPREP,
    TESTDMASUBMIT,
    TESTDMAPENDING,
    TESTDMAPAUSE,
    TESTDMARESUME,
    TESTDMAPOINTER,

    TESTDSPGETSERVICENAME,
    TESTDSPGETDAINAME,

    TESTDATAFROMCARD,
    TESTBYTESTOFRAMES,
    TESTDATABIGENDIANCHANGE,
    TESTFRAMATTOBITWIDTH,
    TESTSETPCMINFO,
    TESTSETRENDERBUFINFO,
    TESTSETCAPTUREBUFINFO,
    TESTPCMWRITE,
    TESTPCMREAD,
    TESTPCMMMAPWRITE,
    TESTPCMMMAPREAD,
    TESTRENDEROPEN,
    TESTCAPTUREOPEN,
    TESTRENDERCLOSE,
    TESTPCMPOINTER,
    TESTCAPTURECLOSE,
    TESTHWPARAMS,
    TESTRENDERPREPARE,
    TESTCAPTUREPREPARE,
    TESTRENDERTRIGGER,
    TESTCAPTURETRIGGER,
};

#endif /* AUDIO_COMMON_TEST_H */
