include $(srctree)/config/sdk-a7-mcu.mk

#T=best2600w_aiot
KERNEL=FREERTOS
PSRAM_ENABLE=1
NET_JANSSON_SUPPORT=0
NET_CJSON_SUPPORT=0
UTILS_BES_KV=1
GEN_SDK_LIB_NET=1
RF_TX_CONTROL_IO=100
WIFI_RF_OUT_FEM_SW=0
PA_ENABLE_IO=21
WIFI_BT_COEX_FDD=0
WIFI_BT_COEX_HYBRID=0
CP_BOOT=1
PSRAMCP_SIZE=0x100000
FAST_TIMER_COMPENSATE=1 
NET_MBEDTLS_TESTS_SUPPORT=1
MBEDTLS_FS_IO=1
DUAL_BAND=1
#added for CMD_LIST_COUNT&cmd_send()
CONSOLE_CMD_EXT=1

#audio prompt
VOICE_PROMPT=1


export BES_TEST=1

# use all free PSRAM as OS HEAP instead of OS_HEAP_SIZE
KBUILD_CPPFLAGS += -DOS_HEAP_USE_ALL
LDS_SECTION_FLAGS += -DOS_HEAP_USE_ALL


export MCU_TFLM_ENABLE=0
ifeq ($(MCU_TFLM_ENABLE),1)
KBUILD_CPPFLAGS += -DMCU_TFLM_ENABLE
endif

export BT_MEDIA_SUPPORT_LPLAYER=1
export LPLAYER_A2DP_SUPPORT_PREEMPT_WITHOUT_RESUME=0
ifeq ($(strip $(BT_MEDIA_SUPPORT_LPLAYER)),1)
KBUILD_CPPFLAGS += -DBT_MEDIA_SUPPORT_LPLAYER

ifeq ($(strip $(LPLAYER_A2DP_SUPPORT_PREEMPT_WITHOUT_RESUME)),1)
KBUILD_CPPFLAGS += -DLPLAYER_A2DP_SUPPORT_PREEMPT_WITHOUT_RESUME
endif

endif


export FTR_RESUME_MIC_CAPTURE_AFTER_CALL=1
ifeq ($(strip $(FTR_RESUME_MIC_CAPTURE_AFTER_CALL)),1)
KBUILD_CPPFLAGS += -DFTR_RESUME_MIC_CAPTURE_AFTER_CALL
endif

export TEST_BLE_SERVICE=0
ifeq ($(strip $(TEST_BLE_SERVICE)),1)
KBUILD_CPPFLAGS += -DTEST_BLE_SERVICE
endif

export BFDGL=1
ifeq ($(strip $(BFDGL)),1)
KBUILD_CPPFLAGS += -DBFDGL -DCONFIG_DISPLAY_A064 -DI2C1_IOMUX_INDEX=06
#lv_conf.h in ${LV_PROJ}/
export LV_PROJ=demo
KBUILD_CPPFLAGS += -DLV_CONF_INCLUDE_SIMPLE

export LV_SHOW_LOGO=1
ifeq ($(strip $(LV_SHOW_LOGO)),1)
KBUILD_CPPFLAGS += -DLV_SHOW_LOGO
endif


endif