include $(srctree)/config/sdk.mk

#T=cmcp
DEBUG_PORT=4
PSRAMCP_SIZE=0x100000
DUAL_BAND=1
KERNEL=FREERTOS
SECURE_BOOT=0
RF_TX_CONTROL_IO=100
WIFI_RF_OUT_FEM_SW=0
WIFI_BT_COEX_FDD=0
WIFI_BT_COEX_HYBRID=0
GEN_SDK_LIB_NET=0

