/*
 * Copyright (c) 2022-2022 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
#include <chrono>
#include <thread>
#include "testngpp/testngpp.hpp"
#include "helper/test_player.hpp"

using namespace OHOS::Media::Test;

// @fixture(tags=audio_play_slow)
FIXTURE(DataDrivenSinglePlayerTestSlow)
{
    DATA_PROVIDER(myurls, 1,
    DATA_GROUP(std::string(RESOURCE_DIR "/MP3/MP3_LONG_48000_32.mp3")),
    DATA_GROUP(std::string(RESOURCE_DIR "/M4A/MPEG-4_48000_32_LONG.m4a")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/WAV/02-400Hz Stereo 0dB.wav")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/WAV/03-500Hz Stereo 0dB.wav")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/WAV/04-600Hz Stereo 0dB.wav")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/WAV/05-700Hz Stereo 0dB.wav")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/WAV/06-800Hz Stereo 0dB.wav")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/WAV/07-900Hz Stereo 0dB.wav")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/WAV/08-1kHz Stereo 0dB.wav")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/WAV/09-2kHz Stereo 0dB.wav")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/WAV/10-3kHz Stereo 0dB.wav")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/WAV/100Hz-44.1K-sine_0dB.wav")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/WAV/1077205091002.wav")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/WAV/10KHz-stero.wav")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/WAV/11-4kHz Stereo 0dB.wav")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/WAV/12-5kHz Stereo 0dB.wav")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/WAV/12KHz-44.1K-sine_0dB.wav")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/WAV/13-6kHz Stereo 0dB.wav")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/WAV/14-7kHz Stereo 0dB.wav")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/WAV/15-8kHz Stereo 0dB.wav")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/WAV/150Hz-44.1K-sine_0dB.wav")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/WAV/15KHz-44.1K-sine_0dB.wav")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/WAV/16-9kHz Stereo 0dB.wav")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/WAV/17-10kHz Stereo 0dB.wav")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/WAV/18-12kHz Stereo 0dB.wav")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/WAV/180Hz-44.1K-sine_0dB.wav")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/WAV/19-16kHz Stereo 0dB.wav")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/WAV/1KHz-44.1K-sine_-6dB.wav")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/WAV/1KHz-44.1K-sine_0dB.wav")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/WAV/1KHz-stero.wav")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/WAV/1kHz Stereo 0dB.wav")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/WAV/20-20kHz Stereo 0dB.wav")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/WAV/200Hz-44.1K-sine_0dB.wav")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/WAV/20Hz-stero.wav")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/WAV/2kHz Stereo 0dB.wav")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/WAV/AngleAudioEffect-1.wav")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/WAV/Chains.wav")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/WAV/WAV_192k_16bit_2CH_11.wav")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/WAV/WAV_192k_24bit_2CH_11.wav")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/WAV/WAV_192k_32bit_2CH_11.wav")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/WAV/WAV_48k_32bit_2CH_11.wav")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/WAV/WAV_96k_16bit_2CH_11.wav")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/WAV/WAV_96k_24bit_2CH_11.wav")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/WAV/WAV_96k_32bit_2CH_11.wav")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/WAV/chushan-1.wav")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/WAV/chushan.wav")),
    // TO FIX: ffmpeg wav demuxer cause crash  RESOURCE_DIR "/../../../../resource_ext/WAV/dash-runner-8bit.wav
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/WAV/dash-runner-8bit_short.wav")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/WAV/short_music.wav")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/WAV/sound_voices-1.wav")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/WAV/sound_voices.wav")),

    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/AAC/AACLC_1channel_001.aac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/AAC/00-200Hz Stereo 0dB.aac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/AAC/01-300Hz Stereo 0dB.aac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/AAC/02-400Hz Stereo 0dB.aac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/AAC/03-500Hz Stereo 0dB.aac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/AAC/04-600Hz Stereo 0dB.aac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/AAC/05-700Hz Stereo 0dB.aac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/AAC/06-800Hz Stereo 0dB.aac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/AAC/07-900Hz Stereo 0dB.aac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/AAC/08-1kHz Stereo 0dB.aac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/AAC/09-2kHz Stereo 0dB.aac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/AAC/1.aac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/AAC/10-3kHz Stereo 0dB.aac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/AAC/100Hz-44.1K-sine_0dB.aac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/AAC/11-4kHz Stereo 0dB.aac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/AAC/12-5kHz Stereo 0dB.aac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/AAC/12KHz-44.1K-sine_0dB.aac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/AAC/13-6kHz Stereo 0dB.aac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/AAC/14-7kHz Stereo 0dB.aac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/AAC/15-8kHz Stereo 0dB.aac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/AAC/150Hz-44.1K-sine_0dB.aac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/AAC/15KHz-44.1K-sine_0dB.aac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/AAC/16-9kHz Stereo 0dB.aac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/AAC/17-10kHz Stereo 0dB.aac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/AAC/171005793.aac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/AAC/18-12kHz Stereo 0dB.aac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/AAC/180Hz-44.1K-sine_0dB.aac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/AAC/19-16kHz Stereo 0dB.aac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/AAC/1KHz-44.1K-sine_-6dB.aac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/AAC/1KHz-44.1K-sine_0dB.aac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/AAC/1kHz Stereo 0dB.aac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/AAC/20-20kHz Stereo 0dB.aac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/AAC/200Hz-44.1K-sine_0dB.aac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/AAC/2kHz Stereo 0dB.aac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/AAC/AACLC_1channel_001.aac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/AAC/AM playing.aac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/AAC/AM radio.aac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/AAC/AM.aac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/AAC/Bye_Bye_Bye-Lovestoned-19466604.aac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/AAC/Call to 1669.aac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/AAC/Chains.aac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/AAC/Chains~1.aac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/AAC/Chains~2.aac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/AAC/Chains~3.aac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/AAC/Chains~4.aac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/AAC/Chains~5.aac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/AAC/Change frequency 97.5 FM.aac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/AAC/Change to a route that avoids tolls..aac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/AAC/Change to an economical route.aac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/AAC/Change to the nearest route.aac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/AAC/Changed to AM.aac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/AAC/Changed to FM.aac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/AAC/Chinese148755.aac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/AAC/Close the window on passenger side.aac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/AAC/Close the window on the drive side.aac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/AAC/Cover27487643.aac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/AAC/Save as a favorite son.aac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/AAC/Set play mode loop all---All swirls.aac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/AAC/Set play mode shuffle---Play randomly.aac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/AAC/Switch to fastest route.aac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/AAC/a2002011001-e02-8kHz.aac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/AAC/add home address.aac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/AAC/add work address.aac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/AAC/ail_ext.aac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/AAC/ail_int.aac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/AAC/blow face foot.aac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/AAC/blow face.aac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/AAC/blow foot.aac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/AAC/blow_windscreen.aac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/AAC/blow_windscreen_foot.aac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/AAC/bridgegril85595213.aac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/AAC/call back.aac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/AAC/callcenter.aac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/AAC/cancel.aac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/AAC/close the AC .aac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/AAC/close the roof .aac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/AAC/cool down the temperature .aac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/AAC/dash-runner-8bit.aac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/AAC/dash-runner-8bit_short.aac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/AAC/decrease the fan speed please.aac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/AAC/defrost_off.aac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/AAC/defrost_on.aac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/AAC/j_fa2_hev2.aac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/AAC/m_a_he.aac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/AAC/meet.aac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/AAC/out.aac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/AAC/out~1.aac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/AAC/resume music.aac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/AAC/sample_16kHz.aac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/AAC/sample_16kHz_2.aac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/AAC/sample_32kHz.aac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/AAC/sample_441.aac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/AAC/short_music.aac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/AAC/size up.aac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/AAC/sounds on please.aac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/AAC/take me back to the previous .aac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/AAC/take me to settings.aac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/AAC/test_48000Hz_32bit_1Channel.aac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/AAC/test_file_acc.aac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/AAC/tune to 837 AM.aac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/AAC/turn down the light to the lowest.aac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/AAC/turn on the maximum fan speed.aac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/AAC/want to add this station to favorite .aac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/AAC/warmer on .aac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/AAC/yes.aac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/AAC/zoom out the map.aac")),

    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/MP3/002-100Hz-stero.mp3")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/MP3/003-1KHz-stero.mp3")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/MP3/004-10KHz-stero.mp3")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/MP3/005-20KHz-stero.mp3")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/MP3/006-1KHz-L.mp3")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/MP3/007-1KHz-R.mp3")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/MP3/008-10KHz-L.mp3")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/MP3/009-10KHz-R.mp3")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/MP3/10KHz-stero.mp3")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/MP3/1KHz-stero.mp3")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/MP3/20Hz-stero.mp3")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/MP3/20kHz.mp3")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/MP3/456.mp3")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/MP3/add home address.mp3")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/MP3/add work address.mp3")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/MP3/ail_ext.mp3")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/MP3/ail_int.mp3")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/MP3/AM playing.mp3")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/MP3/AM radio.mp3")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/MP3/AM.mp3")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/MP3/angel_audio.mp3")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/MP3/attach_picture.mp3")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/MP3/background.mp3")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/MP3/blow face foot.mp3")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/MP3/blow face.mp3")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/MP3/blow foot.mp3")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/MP3/blow_windscreen.mp3")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/MP3/blow_windscreen_foot.mp3")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/MP3/call back.mp3")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/MP3/Call to 1669.mp3")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/MP3/callcenter.mp3")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/MP3/cancel.mp3")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/MP3/Catherine.mp3")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/MP3/Chains.mp3")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/MP3/Change frequency 97.5 FM.mp3")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/MP3/Change to a route that avoids tolls..mp3")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/MP3/Change to an economical route.mp3")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/MP3/Change to the nearest route.mp3")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/MP3/Changed to AM.mp3")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/MP3/Changed to FM.mp3")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/MP3/clap.mp3")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/MP3/close the AC .mp3")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/MP3/close the roof .mp3")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/MP3/Close the window on passenger side.mp3")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/MP3/Close the window on the drive side.mp3")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/MP3/cool down the temperature .mp3")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/MP3/dash-runner-8bit_short.mp3")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/MP3/decrease the fan speed please.mp3")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/MP3/defrost_off.mp3")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/MP3/defrost_on.mp3")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/MP3/dream_it_possible.mp3")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/MP3/foreverLove.mp3")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/MP3/resume music.mp3")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/MP3/Set play mode loop all---All swirls.mp3")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/MP3/Set play mode shuffle---Play randomly.mp3")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/MP3/short_music.mp3")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/MP3/size up.mp3")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/MP3/sounds on please.mp3")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/MP3/Switch to fastest route.mp3")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/MP3/take me back to the previous .mp3")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/MP3/take me to settings.mp3")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/MP3/test-2sec.mp3")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/MP3/Track02_1kHz.mp3")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/MP3/Track03_17Hz.mp3")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/MP3/Track04_127Hz.mp3")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/MP3/Track05_997Hz.mp3")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/MP3/Track06_10kHz.mp3")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/MP3/Track07_20kHz.mp3")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/MP3/Track08_MUTE.mp3")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/MP3/Track09_1kHz_L.mp3")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/MP3/Track11_1kHz_R.mp3")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/MP3/tune to 837 AM.mp3")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/MP3/turn down the light to the lowest.mp3")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/MP3/turn on the maximum fan speed.mp3")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/MP3/want to add this station to favorite .mp3")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/MP3/warmer on .mp3")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/MP3/xiaoluluanzhuang-1.mp3")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/MP3/xiaoluluanzhuang.mp3")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/MP3/yes.mp3")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/MP3/zoom out the map.mp3")),

    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/APE/00-200Hz Stereo 0dB.ape")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/APE/01-300Hz Stereo 0dB.ape")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/APE/02-400Hz Stereo 0dB.ape")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/APE/03-500Hz Stereo 0dB.ape")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/APE/04-600Hz Stereo 0dB.ape")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/APE/05-700Hz Stereo 0dB.ape")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/APE/06-800Hz Stereo 0dB.ape")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/APE/07-900Hz Stereo 0dB.ape")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/APE/08-1kHz Stereo 0dB.ape")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/APE/09-2kHz Stereo 0dB.ape")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/APE/1.ape")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/APE/10-3kHz Stereo 0dB.ape")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/APE/100Hz-44.1K-sine_0dB.ape")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/APE/1077205091002.ape")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/APE/11-4kHz Stereo 0dB.ape")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/APE/12-5kHz Stereo 0dB.ape")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/APE/12KHz-44.1K-sine_0dB.ape")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/APE/13-6kHz Stereo 0dB.ape")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/APE/14-7kHz Stereo 0dB.ape")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/APE/15-8kHz Stereo 0dB.ape")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/APE/150Hz-44.1K-sine_0dB.ape")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/APE/15KHz-44.1K-sine_0dB.ape")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/APE/16-9kHz Stereo 0dB.ape")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/APE/17-10kHz Stereo 0dB.ape")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/APE/171005793.ape")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/APE/18-12kHz Stereo 0dB.ape")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/APE/180Hz-44.1K-sine_0dB.ape")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/APE/19-16kHz Stereo 0dB.ape")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/APE/1kHz Stereo 0dB.ape")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/APE/1KHz-44.1K-sine_-6dB.ape")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/APE/1KHz-44.1K-sine_0dB.ape")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/APE/20-20kHz Stereo 0dB.ape")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/APE/200Hz-44.1K-sine_0dB.ape")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/APE/2kHz Stereo 0dB.ape")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/APE/a2002011001-e02-8kHz.ape")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/APE/add home address.ape")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/APE/add work address.ape")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/APE/ail_ext.ape")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/APE/ail_int.ape")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/APE/AM playing.ape")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/APE/AM radio.ape")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/APE/AM.ape")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/APE/blow face foot.ape")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/APE/blow face.ape")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/APE/blow foot.ape")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/APE/blow_windscreen.ape")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/APE/blow_windscreen_foot.ape")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/APE/bridgegril85595213.ape")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/APE/Bye_Bye_Bye-Lovestoned-19466604.ape")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/APE/call back.ape")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/APE/Call to 1669.ape")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/APE/callcenter.ape")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/APE/cancel.ape")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/APE/Chains.ape")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/APE/Chains~1.ape")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/APE/Chains~2.ape")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/APE/Chains~3.ape")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/APE/Chains~4.ape")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/APE/Chains~5.ape")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/APE/Change frequency 97.5 FM.ape")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/APE/Change to a route that avoids tolls..ape")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/APE/Change to an economical route.ape")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/APE/Change to the nearest route.ape")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/APE/Changed to AM.ape")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/APE/Changed to FM.ape")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/APE/Chinese148755.ape")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/APE/close the AC .ape")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/APE/close the roof .ape")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/APE/Close the window on passenger side.ape")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/APE/Close the window on the drive side.ape")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/APE/cool down the temperature .ape")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/APE/Cover27487643.ape")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/APE/dash-runner-8bit.ape")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/APE/decrease the fan speed please.ape")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/APE/defrost_off.ape")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/APE/defrost_on.ape")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/APE/Iamnotinyourmemory.ape")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/APE/meet.ape")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/APE/out.ape")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/APE/out~1.ape")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/APE/resume music.ape")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/APE/sample_16kHz.ape")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/APE/sample_16kHz_2.ape")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/APE/sample_32kHz.ape")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/APE/sample_441.ape")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/APE/Save as a favorite son.ape")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/APE/Set play mode loop all---All swirls.ape")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/APE/Set play mode shuffle---Play randomly.ape")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/APE/size up.ape")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/APE/sounds on please.ape")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/APE/Switch to fastest route.ape")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/APE/take me back to the previous .ape")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/APE/take me to settings.ape")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/APE/test_file_acc.ape")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/APE/tune to 837 AM.ape")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/APE/turn down the light to the lowest.ape")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/APE/turn on the maximum fan speed.ape")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/APE/want to add this station to favorite .ape")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/APE/warmer on .ape")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/APE/yes.ape")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/APE/zoom out the map.ape")),

    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/FLAC/00-200Hz Stereo 0dB.flac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/FLAC/01-300Hz Stereo 0dB.flac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/FLAC/02-400Hz Stereo 0dB.flac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/FLAC/03-500Hz Stereo 0dB.flac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/FLAC/04-600Hz Stereo 0dB.flac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/FLAC/05-700Hz Stereo 0dB.flac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/FLAC/06-800Hz Stereo 0dB.flac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/FLAC/07-900Hz Stereo 0dB.flac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/FLAC/08-1kHz Stereo 0dB.flac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/FLAC/09-2kHz Stereo 0dB.flac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/FLAC/1.flac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/FLAC/10-3kHz Stereo 0dB.flac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/FLAC/100Hz-44.1K-sine_0dB.flac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/FLAC/11-4kHz Stereo 0dB.flac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/FLAC/12-5kHz Stereo 0dB.flac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/FLAC/12KHz-44.1K-sine_0dB.flac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/FLAC/13-6kHz Stereo 0dB.flac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/FLAC/14-7kHz Stereo 0dB.flac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/FLAC/15-8kHz Stereo 0dB.flac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/FLAC/150Hz-44.1K-sine_0dB.flac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/FLAC/15KHz-44.1K-sine_0dB.flac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/FLAC/16-9kHz Stereo 0dB.flac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/FLAC/17-10kHz Stereo 0dB.flac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/FLAC/171005793.flac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/FLAC/18-12kHz Stereo 0dB.flac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/FLAC/180Hz-44.1K-sine_0dB.flac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/FLAC/19-16kHz Stereo 0dB.flac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/FLAC/1kHz Stereo 0dB.flac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/FLAC/1KHz-44.1K-sine_-6dB.flac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/FLAC/1KHz-44.1K-sine_0dB.flac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/FLAC/20-20kHz Stereo 0dB.flac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/FLAC/200Hz-44.1K-sine_0dB.flac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/FLAC/20kHz.flac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/FLAC/2kHz Stereo 0dB.flac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/FLAC/a2002011001-e02-8kHz.flac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/FLAC/add home address.flac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/FLAC/add work address.flac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/FLAC/ail_ext.flac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/FLAC/ail_int.flac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/FLAC/AM playing.flac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/FLAC/AM radio.flac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/FLAC/AM.flac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/FLAC/blow face foot.flac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/FLAC/blow face.flac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/FLAC/blow foot.flac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/FLAC/blow_windscreen.flac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/FLAC/blow_windscreen_foot.flac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/FLAC/bridgegril85595213.flac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/FLAC/Bye_Bye_Bye-Lovestoned-19466604.flac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/FLAC/call back.flac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/FLAC/Call to 1669.flac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/FLAC/callcenter.flac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/FLAC/cancel.flac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/FLAC/Chains.flac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/FLAC/Chains~1.flac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/FLAC/Chains~2.flac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/FLAC/Chains~3.flac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/FLAC/Chains~4.flac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/FLAC/Chains~5.flac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/FLAC/Change frequency 97.5 FM.flac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/FLAC/Change to a route that avoids tolls..flac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/FLAC/Change to an economical route.flac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/FLAC/Change to the nearest route.flac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/FLAC/Changed to AM.flac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/FLAC/Changed to FM.flac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/FLAC/Chinese148755.flac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/FLAC/close the AC .flac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/FLAC/close the roof .flac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/FLAC/Close the window on passenger side.flac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/FLAC/Close the window on the drive side.flac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/FLAC/cool down the temperature .flac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/FLAC/Cover27487643.flac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/FLAC/dash-runner-8bit.flac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/FLAC/dash-runner-8bit_short.flac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/FLAC/decrease the fan speed please.flac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/FLAC/defrost_off.flac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/FLAC/defrost_on.flac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/FLAC/meet.flac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/FLAC/out.flac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/FLAC/out~1.flac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/FLAC/resume music.flac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/FLAC/sample_16kHz.flac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/FLAC/sample_16kHz_2.flac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/FLAC/sample_32kHz.flac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/FLAC/sample_441.flac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/FLAC/Save as a favorite son.flac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/FLAC/Set play mode loop all---All swirls.flac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/FLAC/Set play mode shuffle---Play randomly.flac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/FLAC/short_music.flac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/FLAC/size up.flac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/FLAC/sounds on please.flac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/FLAC/Switch to fastest route.flac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/FLAC/take me back to the previous .flac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/FLAC/take me to settings.flac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/FLAC/test_48000Hz_32bit_1Channel.flac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/FLAC/test_file_acc.flac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/FLAC/tune to 837 AM.flac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/FLAC/turn down the light to the lowest.flac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/FLAC/turn on the maximum fan speed.flac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/FLAC/want to add this station to favorite .flac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/FLAC/warmer on .flac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/FLAC/whitenoise.flac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/FLAC/yes.flac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/FLAC/zoom out the map.flac")),

    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/OGG/01_Minimal_tone.ogg")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/OGG/01_Sherbet.ogg")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/OGG/02_Haze.ogg")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/OGG/02_Peaceful_dreaming.ogg")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/OGG/03_Bubbles.ogg")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/OGG/03_Twinkling_bell.ogg")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/OGG/04_Pathetique.ogg")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/OGG/04_Transparent_piano.ogg")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/OGG/05_Animato_Tone.ogg")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/OGG/05_One_fine_day.ogg")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/OGG/06_Beat_maker.ogg")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/OGG/06_Stepping_stones.ogg")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/OGG/07_DontPanic.ogg")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/OGG/07_Ringing_to_you.ogg")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/OGG/08_Vocalise.ogg")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/OGG/09_Circus_time.ogg")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/OGG/09_Postbox.ogg")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/OGG/1077205091002.ogg")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/OGG/10_Latino_jazz.ogg")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/OGG/10_Tinkerbell.ogg")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/OGG/11_CaffeineSnake.ogg")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/OGG/11_High_frequency.ogg")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/OGG/12_Sunshine.ogg")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/OGG/12_Tweeters.ogg")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/OGG/13_Oriental_express.ogg")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/OGG/13_Starry_night.ogg")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/OGG/14_A_beat_for_me.ogg")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/OGG/14_Pizzicato.ogg")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/OGG/15_On_my_mind.ogg")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/OGG/15_Pause_tone.ogg")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/OGG/16_Drawing_the_night.ogg")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/OGG/16_Heaven.ogg")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/OGG/17_Pixiedust.ogg")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/OGG/17_Pure_tone.ogg")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/OGG/18_A_cricket_chirps.ogg")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/OGG/18_TaDa.ogg")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/OGG/19_Basic_bell.ogg")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/OGG/19_Morning_breeze.ogg")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/OGG/20_Classic_bell.ogg")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/OGG/20_Cloud.ogg")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/OGG/21_Postman.ogg")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/OGG/22_On_time.ogg")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/OGG/a.ogg")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/OGG/A_toy_watch.ogg")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/OGG/BeatPlucker.ogg")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/OGG/Big_Easy.ogg")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/OGG/BirdLoop.ogg")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/OGG/Bollywood.ogg")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/OGG/Breeze.ogg")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/OGG/camera_click.ogg")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/OGG/camera_click_short.ogg")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/OGG/CaribbeanIce.ogg")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/OGG/Chains.ogg")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/OGG/Charger_Connection.ogg")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/OGG/CurveBallBlend.ogg")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/OGG/DigitalPhone.ogg")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/OGG/Eastern_Sky.ogg")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/OGG/Effect_Tick.ogg")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/OGG/EtherShake.ogg")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/OGG/Forest.ogg")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/OGG/Funk_Yall.ogg")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/OGG/Gimme_Mo_Town.ogg")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/OGG/Good_Morning.ogg")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/OGG/Growl.ogg")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/OGG/Insert.ogg")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/OGG/KeypressDelete.ogg")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/OGG/KeypressReturn.ogg")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/OGG/KeypressSpacebar.ogg")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/OGG/Light.ogg")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/OGG/Lock.ogg")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/OGG/LoveFlute.ogg")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/OGG/MidEvilJaunt.ogg")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/OGG/Mist.ogg")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/OGG/Morning.ogg")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/OGG/Noisey_One.ogg")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/OGG/No_Limits.ogg")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/OGG/PDD.ogg")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/OGG/Rain.ogg")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/OGG/Road_Trip.ogg")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/OGG/Savannah.ogg")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/OGG/Seville.ogg")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/OGG/Steppin_Out.ogg")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/OGG/Terminated.ogg")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/OGG/TerribleTwos.ogg")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/OGG/Third_Eye.ogg")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/OGG/Ticktac.ogg")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/OGG/TW_Battery_caution.ogg")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/OGG/TW_Call_Disconnect.ogg")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/OGG/TW_Error.ogg")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/OGG/TW_Low_Battery.ogg")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/OGG/TW_Touch.ogg")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/OGG/TW_Unlock.ogg")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/OGG/TW_Unlock_Glass.ogg")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/OGG/TW_Unlock_Puzzle.ogg")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/OGG/TW_Waterdrop.ogg")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/OGG/Unlock.ogg")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/OGG/VeryAlarmed.ogg")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/OGG/Victory.ogg")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/OGG/VideoRecord.ogg")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/OGG/World.ogg")),

    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/M4A/00-200Hz Stereo 0dB.m4a")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/M4A/01-300Hz Stereo 0dB.m4a")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/M4A/02-400Hz Stereo 0dB.m4a")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/M4A/03-500Hz Stereo 0dB.m4a")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/M4A/04-600Hz Stereo 0dB.m4a")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/M4A/05-700Hz Stereo 0dB.m4a")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/M4A/06-800Hz Stereo 0dB.m4a")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/M4A/07-900Hz Stereo 0dB.m4a")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/M4A/08-1kHz Stereo 0dB.m4a")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/M4A/09-2kHz Stereo 0dB.m4a")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/M4A/1.m4a")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/M4A/10-3kHz Stereo 0dB.m4a")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/M4A/100Hz-44.1K-sine_0dB.m4a")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/M4A/11-4kHz Stereo 0dB.m4a")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/M4A/12-5kHz Stereo 0dB.m4a")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/M4A/12KHz-44.1K-sine_0dB.m4a")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/M4A/13-6kHz Stereo 0dB.m4a")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/M4A/14-7kHz Stereo 0dB.m4a")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/M4A/15-8kHz Stereo 0dB.m4a")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/M4A/150Hz-44.1K-sine_0dB.m4a")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/M4A/15KHz-44.1K-sine_0dB.m4a")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/M4A/16-9kHz Stereo 0dB.m4a")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/M4A/17-10kHz Stereo 0dB.m4a")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/M4A/171005793.m4a")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/M4A/18-12kHz Stereo 0dB.m4a")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/M4A/180Hz-44.1K-sine_0dB.m4a")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/M4A/19-16kHz Stereo 0dB.m4a")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/M4A/1kHz Stereo 0dB.m4a")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/M4A/1KHz-44.1K-sine_-6dB.m4a")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/M4A/1KHz-44.1K-sine_0dB.m4a")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/M4A/20-20kHz Stereo 0dB.m4a")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/M4A/200Hz-44.1K-sine_0dB.m4a")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/M4A/2kHz Stereo 0dB.m4a")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/M4A/a2002011001-e02-8kHz.m4a")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/M4A/add home address.m4a")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/M4A/add work address.m4a")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/M4A/ail_ext.m4a")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/M4A/ail_int.m4a")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/M4A/AM playing.m4a")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/M4A/AM radio.m4a")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/M4A/AM.m4a")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/M4A/blow face foot.m4a")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/M4A/blow face.m4a")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/M4A/blow foot.m4a")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/M4A/blow_windscreen.m4a")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/M4A/blow_windscreen_foot.m4a")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/M4A/bridgegril85595213.m4a")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/M4A/Bye_Bye_Bye-Lovestoned-19466604.m4a")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/M4A/call back.m4a")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/M4A/Call to 1669.m4a")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/M4A/callcenter.m4a")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/M4A/cancel.m4a")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/M4A/Chains.m4a")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/M4A/Chains~1.m4a")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/M4A/Chains~2.m4a")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/M4A/Chains~3.m4a")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/M4A/Chains~4.m4a")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/M4A/Chains~5.m4a")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/M4A/Change frequency 97.5 FM.m4a")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/M4A/Change to a route that avoids tolls..m4a")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/M4A/Change to an economical route.m4a")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/M4A/Change to the nearest route.m4a")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/M4A/Changed to AM.m4a")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/M4A/Changed to FM.m4a")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/M4A/Chinese148755.m4a")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/M4A/close the AC .m4a")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/M4A/close the roof .m4a")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/M4A/Close the window on passenger side.m4a")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/M4A/Close the window on the drive side.m4a")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/M4A/cool down the temperature .m4a")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/M4A/Cover27487643.m4a")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/M4A/dash-runner-8bit.m4a")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/M4A/decrease the fan speed please.m4a")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/M4A/defrost_off.m4a")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/M4A/defrost_on.m4a")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/M4A/meet.m4a")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/M4A/out.m4a")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/M4A/out~1.m4a")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/M4A/piano.m4a")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/M4A/resume music.m4a")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/M4A/sample_16kHz.m4a")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/M4A/sample_16kHz_2.m4a")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/M4A/sample_32kHz.m4a")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/M4A/sample_441.m4a")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/M4A/Save as a favorite son.m4a")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/M4A/Set play mode loop all---All swirls.m4a")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/M4A/Set play mode shuffle---Play randomly.m4a")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/M4A/short_music.m4a")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/M4A/size up.m4a")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/M4A/sounds on please.m4a")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/M4A/Switch to fastest route.m4a")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/M4A/take me back to the previous .m4a")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/M4A/take me to settings.m4a")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/M4A/test_48000Hz_32bit_1Channel.m4a")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/M4A/test_file_acc.m4a")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/M4A/tune to 837 AM.m4a")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/M4A/turn down the light to the lowest.m4a")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/M4A/turn on the maximum fan speed.m4a")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/M4A/want to add this station to favorite .m4a")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/M4A/warmer on .m4a")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/M4A/Whistling_Down_the_Road-1.m4a")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/M4A/Whistling_Down_the_Road.m4a")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/M4A/yes.m4a")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/M4A/zoom out the map.m4a")),
    DATA_GROUP(std::string("http://img.51miz.com/preview/sound/00/26/73/51miz-S267356-423D33372.mp3")),
    DATA_GROUP(std::string("https://img.51miz.com/preview/sound/00/26/73/51miz-S267356-423D33372.mp3")));

	// @test(data="myurls")
    PTEST((std::string url), Test single player play url music, and finished automatically)
    {
        std::unique_ptr<TestPlayer> player = TestPlayer::Create();
        ASSERT_EQ(0, player->SetSource(TestSource(url)));
        ASSERT_EQ(0, player->Prepare());
        ASSERT_EQ(0, player->Play());
        while (player->IsPlaying()) {
            std::this_thread::sleep_for(std::chrono::milliseconds(1000));
        }
    }

    DATA_PROVIDER(specialFileUrls, 1,
    // TO FIX: ffmpeg wav demuxer cause crash  RESOURCE_DIR "/../../../../resource_ext/WAV/dash-runner-8bit.wav
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/AAC/AACLC_1channel_001.aac")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/APE/bridgegril85595213.ape")),
    DATA_GROUP(std::string(RESOURCE_DIR "/../../../../resource_ext/OGG/Chains.ogg")));

    // @test(data="specialFileUrls", tags=debug)
    PTEST((std::string url), Debug single player play url music, and finished automatically)
    {
        std::unique_ptr<TestPlayer> player = TestPlayer::Create();
        ASSERT_EQ(0, player->SetSource(TestSource(url)));
        ASSERT_EQ(0, player->Prepare());
        ASSERT_EQ(0, player->Play());
        while (player->IsPlaying()) {
            std::this_thread::sleep_for(std::chrono::milliseconds(1000));
        }
    }
};